# Generated by Django 5.1.2 on 2024-11-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltvibe', '0013_remove_order_user_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
