# Generated by Django 5.1.2 on 2024-11-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltvibe', '0015_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voltvibe.product'),
        ),
    ]
