# Generated by Django 5.1.2 on 2024-11-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltvibe', '0017_product_description_delete_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
