# Generated by Django 5.0.7 on 2026-02-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltvibe', '0019_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop')], default='phone', max_length=20),
        ),
    ]
